apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bg-chart.fullname" . }}-config
data:
  APP_PORT: "{{ .Values.container.port }}"
  REDIS_MASTER_HOST: {{ .Values.redis_chart.name }}-redis-master
  REDIS_SLAVE_HOST: {{ .Values.redis_chart.name }}-redis-slave
  REDIS_PORT: "{{ .Values.redis_chart.port }}"
