version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: afakharany/birthdaygreeter
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  test:
    docker:
      - image: circleci/redis
      - image: circleci/golang:1.12
    environment: 
      TEST_RESULTS: /tmp/test-results 
    steps:
      - checkout
      - run:
          name: install dockerize
          command: apt-get update && apt-get install -y wget && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Run unit tests
          command: gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml

      
  publish-latest:
    environment:
      IMAGE_NAME: afakharany/birthdaygreeter
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
      - publish-latest:
              requires:
                - build
                - test
              filters:
                branches:
                  only: master