version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: afakharany/birthdaygreeter
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            docker push $IMAGE_NAME:latest
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis
        entrypoint: "redis-server --requirepass mypassword"
    
    environment: 
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"
      REDIS_PASSWORD: mypassword
      working_directory: /go/src/github.com/abohmeed/birthdaygreeter
    steps:
      - checkout
      - run:
          name: get dependancies
          command: |
            env
            go get -v -t -d ./...
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests
          command: gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          context: DockerHub
          filters:
            branches:
              only: master
          requires:
            - test