apiVersion: v1
kind: Service
metadata:
  name: birthdaygreeter-svc
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthdaygreeter-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: afakharany/birthdaygreeter
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-redis
              key: redis-password
        envFrom:
        - configMapRef:
            name: appconfig
        livenessProbe:
          httpGet:
            path: /hello/user
            port: 3000
        readinessProbe:
          exec:
            command:
            - /app/redis-check
          initialDelaySeconds: 5
          periodSeconds: 5