apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: birthdaygreeter-deployment
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: birthdaygreeter-deployment
  targetCPUUtilizationPercentage: 70