replicaCount: 2

redis_chart:
  name: backend
  port: 6379

container:
  port: 3000

image:
  repository: afakharany/birthdaygreeter
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  nodePort: 32000